const LESSON = {
  grade:    'ortaokul',
  week:     '1. Hafta',
  title:    'Donanım, Yazılım ve Bilgisayarın Dört İşi',
  desc:     'Bilgisayarın parçalarını tanı, bir harfin klavyeden ekrana yolculuğunu izle.',
  goals: [
    'Donanımı yazılımdan ayırt edebileceğim.',
    'Girdi, işlem, çıktı ve depolamayı bir örnekle anlatabileceğim.',
    'Klavye, ekran gibi birimleri görevine göre gruplayabileceğim.',
    'Telefonda ve çamaşır makinesinde dört işi bulabileceğim.',
  ],
  sections: [
    { icon:'1', label:'Donanım ve Yazılım', sub:'Dokunulan parça, çalışan program' },
    { icon:'2', label:'Dört İş', sub:'Girdi · İşlem · Çıktı · Depolama' },
    { icon:'3', label:'Etkinlik ve Test', sub:'Sınıflandır, dene, pekiştir' },
  ],
  quiz: [
    { q:'Elif telefonuna yeni bir oyun indirdi. Telefonuna ne eklenmiş oldu?',
      opts:['Yazılım','Donanım','Yeni bir ekran','Daha büyük bir pil'], correct:0,
      fb:'İndirilen oyun bir programdır, yani yazılımdır. Telefonun parçaları değişmedi.' },
    { q:'Hesap makinesi uygulamasında 7 + 5 yazıp “=” tuşuna bastın. Toplama hangi işte yapılır?',
      opts:['Girdi','Çıktı','İşlem','Depolama'], correct:2,
      fb:'Sayıları toplamak işlemdir. Bu işi işlemci yapar; sonuç sonra ekranda görünür.' },
    { q:'Görseldeki cihaz bilgisayarın hangi işini yapar?<span class="q-gorsel"><!--@dahil:svg-yazici.svg--></span>',
      opts:['Girdi','Çıktı','İşlem','Depolama'], correct:1,
      fb:'Yazıcı, bilgisayardaki belgeyi kâğıda basar. Sonucu dışarı verdiği için çıktı birimidir.' },
    { q:'Çamaşır makinesinin program düğmesini “Hızlı yıkama”ya çevirdin. Bu hangi iştir?',
      opts:['Çıktı','Depolama','İşlem','Girdi'], correct:3,
      fb:'Düğmeyle makineye bilgi veriyorsun. Makineye bilgi vermek girdidir.' },
    { q:'Derinleş (bonus): Tabletin dokunmatik ekranı neden hem girdi hem çıktı birimidir?',
      opts:['Dokunuşu alır ve görüntüyü gösterir','Yalnızca görüntü gösterir','Dosyaları kalıcı saklar','Kararları kendisi verir'], correct:0,
      fb:'Dokunmatik ekran dokunuşunu alır (girdi) ve sonucu gösterir (çıktı). Bu soru puanını düşürmez.' },
  ],
  doneMsg: 'Artık donanımı, yazılımı ve bilgisayarın dört işini biliyorsun!',
};

const SLIDE_LABELS = [
  '1. Kapak',
  '2. Hedefler',
  '3. Isınma: Tahmin Et',
  '4. Adım 1: Donanım',
  '5. Adım 2: Yazılım',
  '6. Adım 3: Girdi',
  '7. Adım 4: İşlem',
  '8. Adım 5: Çıktı',
  '9. Adım 6: Depolama',
  '10. Etkinlik: Donanım mı, Yazılım mı?',
  '11. Etkinlik: Dört İş Kutusu',
  '12. Derinleş',
  '13. Özet',
  '14. Bilgi Testi',
  '15. Tebrikler!',
];
