const LESSON = {
  grade:    'ortaokul',
  week:     '10. Hafta',
  title:    'Atölye 1: Kasayı Açma ve RAM Sök–Tak',
  desc:     'Önce 3D provada izle, sonra gerçek bilgisayarda aynı adımı grubunla yap.',
  goals: [
    'Güvenlik kontrolünü yapıp kasanın yan kapağını açabileceğim.',
    'Kasadaki parçaları bulup etiketleyebileceğim.',
    'RAM\'i mandallarını açarak yuvasından çıkarabileceğim.',
    'RAM\'i çentiği doğru yöne bakacak şekilde takabileceğim.',
  ],
  sections: [
    { icon:'1', label:'Güvenlik ve Kapak', sub:'Fiş, bileklik, vidalar' },
    { icon:'2', label:'Parçaları Tanı', sub:'Bul ve etiketle' },
    { icon:'3', label:'RAM Sök–Tak', sub:'Mandal, çentik, klik' },
  ],
  quiz: [
    { q:'Ayşe’nin grubu kasayı açmaya hazırlanıyor. İlk olarak ne yapmalılar?',
      opts:['Fişi prizden çekmeliler','Bilgisayarı açık bırakmalılar','Vidaları hemen sökmeliler','RAM\'i yerinden çekmeliler'], correct:0,
      fb:'Kasa açılmadan önce fiş her zaman prizden çekilir. Sonra antistatik bileklik takılır.' },
    { q:'Görselde turuncu çerçeveyle gösterilen parça hangisidir?<span class="q-gorsel"><!--@dahil:svg-quiz-ram.svg--></span>',
      opts:['Ekran kartı','Güç kaynağı','RAM','İşlemci'], correct:2,
      fb:'Anakarttaki uzun, ince yuvaya dik takılan, üzerinde çipler olan kart RAM\'dir.' },
    { q:'RAM\'i yuvasından çıkarmak için önce ne yapılır?',
      opts:['RAM yana doğru çekilir','İki uçtaki mandal dışa doğru açılır','Anakart yerinden sökülür','Kasa ters çevrilir'], correct:1,
      fb:'Mandallar açılınca RAM biraz yükselir. Sonra iki kenarından tutulup düz yukarı çekilir.' },
    { q:'Emre RAM\'i yuvaya bastırıyor ama RAM girmiyor. En olası neden hangisidir?',
      opts:['RAM çok soğuk','Monitör kapalı','Kasa fanı duruyor','RAM ters tutuldu; çentik çıkıntıya denk gelmiyor'], correct:3,
      fb:'Çentik çıkıntıya denk gelmediği için RAM oturmaz. Çentik merkezde değildir; RAM çevrilip çentik çıkıntıya hizalanmalıdır.' },
    { q:'Derinleş (bonus): RAM etiketinde “8GB” yazıyor. Bu neyi gösterir?',
      opts:['Belleğin kapasitesini','Belleğin rengini','Takıldığı yuvanın numarasını','Üretim yılını'], correct:0,
      fb:'8GB, modülün bellek kapasitesidir. İki tane 8GB modül takılıysa toplam 16GB olur. Bu soru puanını düşürmez.' },
  ],
  doneMsg: 'Kasayı güvenle açtın, parçaları tanıdın ve RAM\'i doğru yönde taktın!',
};

const SLIDE_LABELS = [
  '1. Kapak',
  '2. Hedefler',
  '3. Isınma: Tahmin Et',
  '4. Malzemeler ve Roller',
  '5. Adım 1: Güvenlik Kontrolü',
  '6. Adım 2: Yan Kapağı Aç',
  '7. Adım 3: Parçaları Bul ve Etiketle',
  '8. Adım 4: RAM\'i Çıkar',
  '9. Adım 5: RAM\'i Tak',
  '10. Adım 6: Fotoğrafla Belgele',
  '11. Etkinlik: RAM\'i Doğru Tak',
  '12. Derinleş',
  '13. Özet',
  '14. Bilgi Testi',
  '15. Tebrikler!',
];
