const LESSON = {
  grade:    'ortaokul',
  week:     '2. Hafta',
  title:    'Bit ve Byte',
  desc:     'Ampulleri yakıp söndür; 1 ve 0’larla sayı ve harf yaz, belleğe kaç fotoğraf sığacağını tahmin et.',
  goals: [
    'Bilgisayarın her şeyi 1 ve 0 ile sakladığını açıklayabileceğim.',
    '8 bitin 1 byte ettiğini ampullerle gösterebileceğim.',
    'KB, MB, GB ve TB birimlerini küçükten büyüğe sıralayabileceğim.',
    'Bir belleğe kaç dosya sığacağını tahmin edip hesaplayabileceğim.',
  ],
  sections: [
    { icon:'1', label:'1 ve 0', sub:'Açık–kapalı, bit, byte' },
    { icon:'2', label:'Harfler Sayıdır', sub:'Ampullerle harf yaz' },
    { icon:'3', label:'Bellek Birimleri', sub:'KB, MB, GB, TB ve tahmin' },
  ],
  quiz: [
    { q:'Bilgisayar harfleri, fotoğrafları ve sesleri nasıl saklar?',
      opts:['1 ve 0’lardan oluşan sayılarla','Küçük kâğıt kopyalarıyla','Renkli ışıklarla','Harfleri olduğu gibi çizerek'], correct:0,
      fb:'Bilgisayarın içinde her şey açık (1) ve kapalı (0) elektrik durumlarıyla, yani sayılarla saklanır.' },
    { q:'Görseldeki ampul sırası kaç bittir ve kaç byte eder?<span class="q-gorsel"><!--@dahil:svg-quiz-ampul.svg--></span>',
      opts:['4 bit, yarım byte','16 bit, 2 byte','8 bit, 1 byte','1 bit, 1 byte'], correct:2,
      fb:'Her ampul bir bittir. 8 ampul 8 bit eder; 8 bit de 1 byte’tır.' },
    { q:'Hangi seçenekte birimler küçükten büyüğe doğru sıralanmıştır?',
      opts:['GB, MB, KB, TB','KB, MB, GB, TB','MB, KB, TB, GB','TB, GB, MB, KB'], correct:1,
      fb:'Her birim bir öncekinin yaklaşık 1000 katıdır: KB, MB, GB, TB.' },
    { q:'Ece’nin telefonunda 8 GB boş yer var. Her video 2 GB. En çok kaç video sığar?',
      opts:['16','2','6','4'], correct:3,
      fb:'8 GB’ı 2 GB’a böleriz: 8 ÷ 2 = 4 video sığar.' },
    { q:'Derinleş (bonus): 1 byte en fazla kaç farklı sayı tutabilir?',
      opts:['256 (0’dan 255’e)','8','100','1000'], correct:0,
      fb:'8 bitle 2 × 2 × 2 × 2 × 2 × 2 × 2 × 2 = 256 farklı desen yapılır: 0’dan 255’e. Bu soru puanını düşürmez.' },
  ],
  doneMsg: 'Artık 1 ve 0’larla sayı ve harf yazabiliyor, bellek birimlerini tanıyorsun!',
};

const SLIDE_LABELS = [
  '1. Kapak',
  '2. Hedefler',
  '3. Isınma: Tahmin Et',
  '4. Adım 1: Açık–Kapalı: 1 ve 0',
  '5. Adım 2: Bit',
  '6. Adım 3: Byte',
  '7. Adım 4: Harfler Sayıdır',
  '8. Adım 5: KB–MB–GB–TB',
  '9. Adım 6: Kaç Fotoğraf Sığar?',
  '10. Etkinlik: Ampullerle Harf Yaz',
  '11. Etkinlik: Bellek Tahmin Oyunu',
  '12. Derinleş',
  '13. Özet',
  '14. Bilgi Testi',
  '15. Tebrikler!',
];
